name: Release deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: ./.github/workflows/npm-publish.yml
    with:
      node-version: "18"
      publish-access: "public"
      prepare-script: >-
        cp package.json LICENSE README.md build/ &&
        cd build &&
        sed -i -e "s~\"version\": \"0.0.0-dev\"~\"version\": \"${GITHUB_REF##*/}\"~" package.json
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}